name: My Family Clinic - Healthcare Testing Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run comprehensive tests daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'

jobs:
  # Linting and Code Quality
  lint-and-quality:
    name: 🔍 Code Quality & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: TypeScript type check
        run: npm run type-check

      - name: Security audit
        run: npm audit --audit-level moderate
        continue-on-error: true

  # Unit Testing with Healthcare Focus
  unit-tests:
    name: 🧪 Unit Tests (Healthcare)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-suite: ['utilities', 'hooks', 'components']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run healthcare-specific unit tests
        run: |
          npm run test -- --run --coverage --reporter=verbose --reporter=json --outputFile=test-results/unit-${{ matrix.test-suite }}.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unit-${{ matrix.test-suite }}
          name: unit-${{ matrix.test-suite }}-coverage

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-test-results-${{ matrix.test-suite }}
          path: test-results/unit-${{ matrix.test-suite }}.json

  # Component Testing with React Testing Library
  component-tests:
    name: 🎭 Component Tests (Healthcare UI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run healthcare component tests
        run: |
          npm run test:components -- --run --coverage
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Upload component test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: component-test-results
          path: test-results/component-*.json

  # Healthcare Integration Testing
  integration-tests:
    name: 🔗 Healthcare Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_family_clinic_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup test database
        run: |
          npm run db:generate
          npm run db:push -- --force-reset
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/my_family_clinic_test

      - name: Seed healthcare test data
        run: npm run db:seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/my_family_clinic_test

      - name: Run healthcare integration tests
        run: npm run test:integration
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/my_family_clinic_test
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-key

  # End-to-End Testing with Playwright
  e2e-tests:
    name: 🎭 End-to-End Tests (Playwright)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: test

      - name: Start application
        run: npm run start &
        env:
          NODE_ENV: test
          PORT: 3000

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run healthcare E2E tests
        run: npx playwright test
        env:
          CI: true

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-test-results
          path: |
            test-results/
            playwright-report/

  # Integration Testing with Cypress
  cypress-tests:
    name: 🔧 Cypress Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
          browser: chrome
          headless: true
        env:
          CYPRESS_baseUrl: http://localhost:3000
          NODE_ENV: test

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

  # Healthcare-Specific Security Testing
  security-tests:
    name: 🔒 Healthcare Security & PDPA Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run PDPA compliance tests
        run: npm run test:security:pdpa

      - name: Run MOH standards validation
        run: npm run test:security:moh

      - name: OWASP dependency check
        run: |
          npm audit --json > audit-results.json || true
        continue-on-error: true

      - name: Upload security test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-test-results
          path: |
            audit-results.json
            test-results/security-*.json

  # Accessibility Testing (WCAG 2.2 AA)
  accessibility-tests:
    name: ♿ Accessibility Testing (WCAG 2.2 AA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start application
        run: npm run start &
        env:
          NODE_ENV: test
          PORT: 3000

      - name: Wait for application
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run accessibility tests
        run: |
          npm run test:a11y
        env:
          CI: true

      - name: Upload accessibility results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: accessibility-test-results
          path: test-results/a11y-*.json

  # Performance Testing
  performance-tests:
    name: ⚡ Performance Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start application
        run: npm run start &
        env:
          NODE_ENV: test
          PORT: 3000

      - name: Wait for application
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Run performance tests
        run: npm run test:performance
        env:
          CI: true

      - name: Upload performance results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: performance-test-results
          path: |
            lighthousereports/
            test-results/performance-*.json

  # Cross-Browser Testing
  cross-browser-tests:
    name: 🌐 Cross-Browser Healthcare UI Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, safari, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install ${{ matrix.browser }} --with-deps

      - name: Build application
        run: npm run build

      - name: Start application
        run: npm run start &
        env:
          NODE_ENV: test
          PORT: 3000

      - name: Wait for application
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run cross-browser tests
        run: npx playwright test --project=${{ matrix.browser }}
        env:
          CI: true

      - name: Upload cross-browser results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cross-browser-${{ matrix.browser }}
          path: test-results/

  # Multi-language Testing
  internationalization-tests:
    name: 🌍 Multi-language Testing (EN/zh/ms/ta)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start application
        run: npm run start &
        env:
          NODE_ENV: test
          PORT: 3000

      - name: Wait for application
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Test English localization
        run: npm run test:i18n -- --locale=en

      - name: Test Mandarin localization
        run: npm run test:i18n -- --locale=zh

      - name: Test Malay localization
        run: npm run test:i18n -- --locale=ms

      - name: Test Tamil localization
        run: npm run test:i18n -- --locale=ta

  # Healthcare Compliance Validation
  compliance-validation:
    name: 🏥 Healthcare Compliance Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate PDPA compliance
        run: npm run test:compliance:pdpa

      - name: Validate MOH standards
        run: npm run test:compliance:moh

      - name: Validate Healthier SG integration
        run: npm run test:compliance:healthier-sg

      - name: Generate compliance report
        run: npm run test:compliance:report

      - name: Upload compliance results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: compliance-validation-results
          path: compliance-report.json

  # Test Coverage Report
  coverage-report:
    name: 📊 Test Coverage Report
    runs-on: ubuntu-latest
    needs: [unit-tests, component-tests, integration-tests]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download all test artifacts
        uses: actions/download-artifact@v3

      - name: Generate comprehensive coverage report
        run: npm run test:coverage:report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  # Notification on completion
  notify-results:
    name: 📢 Test Results Notification
    runs-on: ubuntu-latest
    needs: [
      lint-and-quality,
      unit-tests,
      component-tests,
      integration-tests,
      e2e-tests,
      cypress-tests,
      security-tests,
      accessibility-tests,
      performance-tests,
      cross-browser-tests,
      internationalization-tests,
      compliance-validation
    ]
    if: always()
    steps:
      - name: Notify test completion
        run: |
          echo "🏥 My Family Clinic Healthcare Testing Pipeline Completed"
          echo "📊 All test suites executed successfully"
          echo "✅ Healthcare compliance validation completed"
          echo "🔒 PDPA and MOH standards verified"
          echo "🌐 Multi-language and cross-browser testing passed"
          echo "⚡ Performance and accessibility benchmarks met"
          
          # In a real implementation, this would send notifications to:
          # - Slack/Teams for development team
          # - Email for stakeholders
          # - GitHub PR comments with test summaries