-- Migration: healthier_sg_remaining_enums
-- Created at: 1762269904

-- CreateEnum
CREATE TYPE "HealthierSGSmokingStatus" AS ENUM ('NEVER_SMOKED', 'FORMER_SMOKER', 'CURRENT_SMOKER', 'OCCASIONAL_SMOKER', 'SECONDHAND_EXPOSURE', 'QUIT_RECENTLY', 'QUIT_LONG_TERM');

-- CreateEnum
CREATE TYPE "HealthierSGExerciseFrequency" AS ENUM ('NEVER', 'RARELY', 'WEEKLY_1_2_TIMES', 'WEEKLY_3_4_TIMES', 'DAILY', 'MULTIPLE_TIMES_DAILY', 'SEDENTARY', 'MODERATE', 'HIGHLY_ACTIVE');

-- CreateEnum
CREATE TYPE "HealthierSGStressLevel" AS ENUM ('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'EXTREME', 'MANAGED', 'UNMANAGED');

-- CreateEnum
CREATE TYPE "HealthierSGAssessmentType" AS ENUM ('INITIAL_HEALTH_ASSESSMENT', 'PERIODIC_HEALTH_REVIEW', 'RISK_ASSESSMENT', 'BEHAVIORAL_ASSESSMENT', 'NUTRITIONAL_ASSESSMENT', 'MENTAL_HEALTH_ASSESSMENT', 'FUNCTIONAL_ASSESSMENT', 'QUALITY_OF_LIFE_ASSESSMENT', 'PROGRAM_READINESS', 'GOAL_SETTING_SESSION');

-- CreateEnum
CREATE TYPE "HealthierSGRiskLevel" AS ENUM ('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'CRITICAL', 'EMERGING', 'MANAGED');

-- CreateEnum
CREATE TYPE "HealthierSGActivityType" AS ENUM ('HEALTH_SCREENING', 'CONSULTATION', 'EDUCATIONAL_SESSION', 'EXERCISE_CLASS', 'NUTRITION_COUNSELING', 'BEHAVIORAL_COUNSELING', 'MEDICATION_REVIEW', 'FOLLOW_UP_VISIT', 'GROUP_SESSION', 'HOME_BASED_ACTIVITY', 'TELEHEALTH_SESSION', 'MONITORING_CHECK');

-- CreateEnum
CREATE TYPE "HealthierSGActivityStatus" AS ENUM ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'MISSED', 'CANCELLED', 'RESCHEDULED', 'REQUIRES_FOLLOW_UP', 'PENDING_DOCUMENTATION');

-- CreateEnum
CREATE TYPE "HealthierSGMilestoneType" AS ENUM ('ENROLLMENT_COMPLETE', 'ASSESSMENT_COMPLETE', 'FIRST_CONSULTATION', 'INTERIM_MILESTONE', 'HEALTH_GOAL_ACHIEVED', 'PROGRAM_COMPLETION', 'BEHAVIOR_CHANGE', 'HEALTH_IMPROVEMENT', 'KNOWLEDGE_ACHIEVEMENT', 'PARTICIPATION_TARGET');

-- CreateEnum
CREATE TYPE "HealthierSGOutcomeType" AS ENUM ('HEALTH_IMPROVEMENT', 'BEHAVIOR_CHANGE', 'RISK_REDUCTION', 'QUALITY_OF_LIFE', 'COST_EFFECTIVENESS', 'PATIENT_SATISFACTION', 'ADHERENCE_RATE', 'PREVENTION_SUCCESS', 'EARLY_DETECTION', 'PROGRAM_ENGAGEMENT');

-- CreateEnum
CREATE TYPE "HealthierSGGoalType" AS ENUM ('WEIGHT_MANAGEMENT', 'BLOOD_PRESSURE_CONTROL', 'DIABETES_MANAGEMENT', 'CHOLESTEROL_MANAGEMENT', 'SMOKING_CESSATION', 'PHYSICAL_ACTIVITY', 'NUTRITION_IMPROVEMENT', 'STRESS_MANAGEMENT', 'MEDICATION_ADHERENCE', 'PREVENTIVE_SCREENING', 'MENTAL_HEALTH', 'FUNCTIONAL_IMPROVEMENT', 'QUALITY_OF_LIFE', 'DISEASE_MANAGEMENT');

-- CreateEnum
CREATE TYPE "HealthierSGGoalPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'URGENT', 'OPTIONAL', 'MANDATORY');

-- CreateEnum
CREATE TYPE "HealthierSGGoalStatus" AS ENUM ('ACTIVE', 'ON_TRACK', 'BEHIND_SCHEDULE', 'ACHIEVED', 'MODIFIED', 'CANCELLED', 'ON_HOLD', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "HealthierSGMotivationLevel" AS ENUM ('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'EXTREMELY_HIGH', 'FLUCTUATING', 'DECLINING');

-- CreateEnum
CREATE TYPE "HealthierSGDifficultyLevel" AS ENUM ('VERY_EASY', 'EASY', 'MODERATE', 'DIFFICULT', 'VERY_DIFFICULT', 'EXTREMELY_CHALLENGING', 'MANAGEABLE');

-- CreateEnum
CREATE TYPE "HealthierSGSatisfactionLevel" AS ENUM ('VERY_DISSATISFIED', 'DISSATISFIED', 'NEUTRAL', 'SATISFIED', 'VERY_SATISFIED', 'EXTREMELY_SATISFIED', 'MIXED_FEELINGS');

-- CreateEnum
CREATE TYPE "HealthierSGAuditAction" AS ENUM ('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'ACCESS_DENIED', 'DATA_EXPORT', 'DATA_IMPORT', 'SYSTEM_ACCESS', 'CONFIGURATION_CHANGE', 'BACKUP', 'RESTORE');

-- CreateEnum
CREATE TYPE "HealthierSGAuditDataSensitivity" AS ENUM ('PUBLIC', 'INTERNAL', 'SENSITIVE', 'HIGHLY_SENSITIVE', 'CONFIDENTIAL', 'RESTRICTED', 'MEDICAL', 'PERSONAL_IDENTIFIABLE');

-- CreateEnum
CREATE TYPE "HealthierSGAuditRiskLevel" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'EMERGENCY', 'MONITORING');

-- CreateEnum
CREATE TYPE "HealthierSGAuditType" AS ENUM ('REGULAR_SCHEDULED', 'COMPLIANCE_AUDIT', 'DATA_QUALITY_AUDIT', 'SECURITY_AUDIT', 'PERFORMANCE_AUDIT', 'FINANCIAL_AUDIT', 'PROGRAM_EFFECTIVENESS', 'INCIDENT_RESPONSE', 'SPOT_CHECK', 'EXTERNAL_AUDIT');

-- CreateEnum
CREATE TYPE "HealthierSGAuditPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'URGENT', 'ROUTINE');

-- CreateEnum
CREATE TYPE "HealthierSGDocumentType" AS ENUM ('IDENTITY_VERIFICATION', 'MEDICAL_RECORDS', 'CONSENT_FORMS', 'ELIGIBILITY_DOCUMENTS', 'BENEFIT_CLAIMS', 'INVOICES_RECEIPTS', 'INSURANCE_DOCUMENTS', 'REFERRAL_LETTERS', 'DISCHARGE_SUMMARIES', 'LAB_RESULTS', 'IMAGING_REPORTS', 'PRESCRIPTION_RECORDS', 'PROGRAM_CERTIFICATES', 'AUDIT_REPORTS', 'COMPLIANCE_DOCUMENTS');

-- CreateEnum
CREATE TYPE "HealthierSGDocumentVerificationStatus" AS ENUM ('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'EXPIRED', 'REQUIRES_RENEWAL', 'CONDITIONALLY_APPROVED');

-- CreateEnum
CREATE TYPE "HealthierSGDocumentAccessLevel" AS ENUM ('PUBLIC', 'RESTRICTED', 'CONFIDENTIAL', 'HIGHLY_CONFIDENTIAL', 'MEDICAL_RECORD', 'AUDIT_ONLY', 'GOVERNMENT_ONLY', 'TIME_LIMITED');;