-- Migration: contact_integration_complete
-- Created at: 1762270061

-- CreateTable
CREATE TABLE "user_contact_preferences" (
    "id" TEXT NOT NULL,
    "userId" TEXT UNIQUE NOT NULL,
    "preferredContactMethod" "ContactMethod" NOT NULL DEFAULT 'EMAIL',
    "secondaryContactMethod" "ContactMethod",
    "emergencyContactMethod" "ContactMethod" NOT NULL DEFAULT 'PHONE',
    "allowDirectContact" BOOLEAN NOT NULL DEFAULT true,
    "allowEmailMarketing" BOOLEAN NOT NULL DEFAULT false,
    "allowSmsUpdates" BOOLEAN NOT NULL DEFAULT true,
    "allowPhoneCalls" BOOLEAN NOT NULL DEFAULT false,
    "allowWhatsAppUpdates" BOOLEAN NOT NULL DEFAULT false,
    "contactAllowedFrom" TEXT,
    "contactAllowedTo" TEXT,
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Singapore',
    "doNotDisturb" BOOLEAN NOT NULL DEFAULT false,
    "medicalUpdatesViaEmail" BOOLEAN NOT NULL DEFAULT true,
    "appointmentReminders" BOOLEAN NOT NULL DEFAULT true,
    "healthGoalReminders" BOOLEAN NOT NULL DEFAULT true,
    "programEnrollmentUpdates" BOOLEAN NOT NULL DEFAULT true,
    "emergencyNotifications" BOOLEAN NOT NULL DEFAULT true,
    "preferredFollowUpTime" INTEGER,
    "contactHistoryAccess" BOOLEAN NOT NULL DEFAULT true,
    "shareContactWithPartners" BOOLEAN NOT NULL DEFAULT false,
    "dataRetentionPeriod" INTEGER NOT NULL DEFAULT 365,
    "contactDataEncrypted" BOOLEAN NOT NULL DEFAULT true,
    "thirdPartySharing" BOOLEAN NOT NULL DEFAULT false,
    "marketingTracking" BOOLEAN NOT NULL DEFAULT false,
    "healthierSgNotifications" BOOLEAN NOT NULL DEFAULT true,
    "healthierSgContactPreferences" JSONB NOT NULL DEFAULT '{}',
    "appointmentRelatedContact" BOOLEAN NOT NULL DEFAULT true,
    "serviceRelatedContact" BOOLEAN NOT NULL DEFAULT true,
    "programEnrollmentContact" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "user_contact_preferences_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "clinic_contact_integration" (
    "id" TEXT NOT NULL,
    "clinicId" TEXT UNIQUE NOT NULL,
    "enableContactForm" BOOLEAN NOT NULL DEFAULT true,
    "autoAssignContact" BOOLEAN NOT NULL DEFAULT true,
    "contactFormCategories" JSONB NOT NULL DEFAULT '[]',
    "showPhoneButton" BOOLEAN NOT NULL DEFAULT true,
    "showEmailButton" BOOLEAN NOT NULL DEFAULT true,
    "showWhatsAppButton" BOOLEAN NOT NULL DEFAULT false,
    "showWalkInOption" BOOLEAN NOT NULL DEFAULT true,
    "emergencyContactEnabled" BOOLEAN NOT NULL DEFAULT true,
    "emergencyHours" JSONB NOT NULL DEFAULT '{}',
    "appointmentQueriesEnabled" BOOLEAN NOT NULL DEFAULT true,
    "appointmentHours" JSONB NOT NULL DEFAULT '{}',
    "serviceContactEnabled" BOOLEAN NOT NULL DEFAULT true,
    "serviceContactMethods" JSONB NOT NULL DEFAULT '[]',
    "specialistDirectContact" BOOLEAN NOT NULL DEFAULT false,
    "healthierSgContactEnabled" BOOLEAN NOT NULL DEFAULT true,
    "healthierSgContactMethods" JSONB NOT NULL DEFAULT '[]',
    "responseTimeCommitments" JSONB NOT NULL DEFAULT '{}',
    "businessHours" JSONB NOT NULL DEFAULT '{}',
    "languageSupport" TEXT[] NOT NULL DEFAULT ARRAY['en', 'zh', 'ms', 'ta'],
    "customFields" JSONB NOT NULL DEFAULT '[]',
    "mandatoryFields" JSONB NOT NULL DEFAULT '[]',
    "fileUploadEnabled" BOOLEAN NOT NULL DEFAULT true,
    "maxFileSize" INTEGER NOT NULL DEFAULT 5242880,
    "allowedFileTypes" TEXT[] NOT NULL DEFAULT ARRAY['pdf', 'jpg', 'png', 'doc', 'docx'],
    "contactTrackingEnabled" BOOLEAN NOT NULL DEFAULT true,
    "conversionGoals" JSONB NOT NULL DEFAULT '[]',
    "performanceMetrics" JSONB NOT NULL DEFAULT '{}',
    "crmIntegrationEnabled" BOOLEAN NOT NULL DEFAULT false,
    "crmConfig" JSONB NOT NULL DEFAULT '{}',
    "webhookEndpoints" JSONB NOT NULL DEFAULT '[]',
    "escalationRules" JSONB NOT NULL DEFAULT '[]',
    "autoResponseEnabled" BOOLEAN NOT NULL DEFAULT true,
    "contactDataRetentionDays" INTEGER NOT NULL DEFAULT 730,
    "encryptionRequired" BOOLEAN NOT NULL DEFAULT true,
    "pdpaCompliance" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "clinic_contact_integration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "doctor_contact_capabilities" (
    "id" TEXT NOT NULL,
    "doctorId" TEXT UNIQUE NOT NULL,
    "allowPatientContact" BOOLEAN NOT NULL DEFAULT true,
    "contactMethodPreferences" JSONB NOT NULL DEFAULT '[]',
    "preferredContactTimes" JSONB NOT NULL DEFAULT '{}',
    "patientEmailEnabled" BOOLEAN NOT NULL DEFAULT true,
    "patientPhoneEnabled" BOOLEAN NOT NULL DEFAULT false,
    "patientWhatsAppEnabled" BOOLEAN NOT NULL DEFAULT false,
    "patientPortalEnabled" BOOLEAN NOT NULL DEFAULT true,
    "emergencyContactEnabled" BOOLEAN NOT NULL DEFAULT true,
    "emergencyAfterHours" BOOLEAN NOT NULL DEFAULT false,
    "appointmentQueries" BOOLEAN NOT NULL DEFAULT true,
    "serviceInquiries" BOOLEAN NOT NULL DEFAULT true,
    "secondOpinionRequests" BOOLEAN NOT NULL DEFAULT false,
    "medicalRecordsRequests" BOOLEAN NOT NULL DEFAULT true,
    "specialtyContactRules" JSONB NOT NULL DEFAULT '[]',
    "conditionSpecificContact" JSONB NOT NULL DEFAULT '[]',
    "procedureRelatedContact" BOOLEAN NOT NULL DEFAULT true,
    "healthierSgEnrollmentSupport" BOOLEAN NOT NULL DEFAULT true,
    "healthierSgContactEnabled" BOOLEAN NOT NULL DEFAULT false,
    "professionalReferrals" BOOLEAN NOT NULL DEFAULT true,
    "colleagueConsultation" BOOLEAN NOT NULL DEFAULT false,
    "medicalEducationRequests" BOOLEAN NOT NULL DEFAULT false,
    "responseTimeCommitments" JSONB NOT NULL DEFAULT '{}',
    "consultationAvailability" JSONB NOT NULL DEFAULT '[]',
    "languageSupport" TEXT[] NOT NULL DEFAULT ARRAY['en', 'zh', 'ms', 'ta'],
    "enableContactForm" BOOLEAN NOT NULL DEFAULT true,
    "autoResponseTemplates" JSONB NOT NULL DEFAULT '[]',
    "contactCategorization" JSONB NOT NULL DEFAULT '[]',
    "patientDataHandling" JSONB NOT NULL DEFAULT '{}',
    "medicalRecordRequests" BOOLEAN NOT NULL DEFAULT true,
    "telemedicineContact" BOOLEAN NOT NULL DEFAULT true,
    "videoConsultationContact" BOOLEAN NOT NULL DEFAULT false,
    "digitalPrescriptionContact" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "doctor_contact_capabilities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_contact_info" (
    "id" TEXT NOT NULL,
    "serviceId" TEXT UNIQUE NOT NULL,
    "enableServiceContact" BOOLEAN NOT NULL DEFAULT true,
    "contactMethods" JSONB NOT NULL DEFAULT '[]',
    "specialistContact" BOOLEAN NOT NULL DEFAULT false,
    "generalContact" BOOLEAN NOT NULL DEFAULT true,
    "preAppointmentContact" BOOLEAN NOT NULL DEFAULT true,
    "preparationQuestions" BOOLEAN NOT NULL DEFAULT true,
    "requirementsInquiry" BOOLEAN NOT NULL DEFAULT true,
    "pricingQueries" BOOLEAN NOT NULL DEFAULT true,
    "followUpQueries" BOOLEAN NOT NULL DEFAULT true,
    "resultsDiscussion" BOOLEAN NOT NULL DEFAULT true,
    "complicationReporting" BOOLEAN NOT NULL DEFAULT true,
    "satisfactionFeedback" BOOLEAN NOT NULL DEFAULT true,
    "medicalHistoryInquiry" BOOLEAN NOT NULL DEFAULT true,
    "riskAssessmentContact" BOOLEAN NOT NULL DEFAULT false,
    "contraindicationQueries" BOOLEAN NOT NULL DEFAULT true,
    "alternativeOptions" BOOLEAN NOT NULL DEFAULT true,
    "healthierSgCoverageInquiry" BOOLEAN NOT NULL DEFAULT true,
    "healthierSgProcessSupport" BOOLEAN NOT NULL DEFAULT true,
    "subsidyInformation" BOOLEAN NOT NULL DEFAULT true,
    "serviceSpecificFields" JSONB NOT NULL DEFAULT '[]',
    "mandatoryQuestions" JSONB NOT NULL DEFAULT '[]',
    "optionalInformation" JSONB NOT NULL DEFAULT '[]',
    "autoRoutingRules" JSONB NOT NULL DEFAULT '[]',
    "specialistAssignment" BOOLEAN NOT NULL DEFAULT false,
    "documentUploadRequired" BOOLEAN NOT NULL DEFAULT false,
    "medicalReportUpload" BOOLEAN NOT NULL DEFAULT true,
    "labResultUpload" BOOLEAN NOT NULL DEFAULT false,
    "imageUpload" BOOLEAN NOT NULL DEFAULT false,
    "medicalDataProtection" BOOLEAN NOT NULL DEFAULT true,
    "consentRequired" BOOLEAN NOT NULL DEFAULT true,
    "dataRetentionPeriod" INTEGER NOT NULL DEFAULT 365,
    "clinicIntegration" BOOLEAN NOT NULL DEFAULT true,
    "doctorIntegration" BOOLEAN NOT NULL DEFAULT true,
    "appointmentSystemIntegration" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "service_contact_info_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "healthier_sg_contact_integration" (
    "id" TEXT NOT NULL,
    "enrollmentId" TEXT UNIQUE NOT NULL,
    "enrollmentCompleted" BOOLEAN NOT NULL DEFAULT false,
    "programSupportContact" BOOLEAN NOT NULL DEFAULT true,
    "programQuestions" BOOLEAN NOT NULL DEFAULT true,
    "serviceNavigation" BOOLEAN NOT NULL DEFAULT true,
    "benefitExplanation" BOOLEAN NOT NULL DEFAULT true,
    "goalSettingContact" BOOLEAN NOT NULL DEFAULT true,
    "goalProgressContact" BOOLEAN NOT NULL DEFAULT false,
    "milestoneCelebration" BOOLEAN NOT NULL DEFAULT false,
    "setbackSupport" BOOLEAN NOT NULL DEFAULT true,
    "clinicTransitionSupport" BOOLEAN NOT NULL DEFAULT true,
    "providerSwitchSupport" BOOLEAN NOT NULL DEFAULT false,
    "serviceModification" BOOLEAN NOT NULL DEFAULT true,
    "appointmentAssistance" BOOLEAN NOT NULL DEFAULT true,
    "regularCheckIns" BOOLEAN NOT NULL DEFAULT false,
    "healthReviewContact" BOOLEAN NOT NULL DEFAULT false,
    "annualReviewContact" BOOLEAN NOT NULL DEFAULT false,
    "programUpdates" BOOLEAN NOT NULL DEFAULT true,
    "benefitChanges" BOOLEAN NOT NULL DEFAULT true,
    "newServices" BOOLEAN NOT NULL DEFAULT false,
    "policyChanges" BOOLEAN NOT NULL DEFAULT true,
    "linkWithMedicalContact" BOOLEAN NOT NULL DEFAULT false,
    "separateHealthierSgContact" BOOLEAN NOT NULL DEFAULT true,
    "emergencyHealthierSgContact" BOOLEAN NOT NULL DEFAULT false,
    "programMilestones" JSONB NOT NULL DEFAULT '[]',
    "milestoneContact" JSONB NOT NULL DEFAULT '[]',
    "completionContact" BOOLEAN NOT NULL DEFAULT false,
    "graduationContact" BOOLEAN NOT NULL DEFAULT false,
    "contactEffectiveness" JSONB NOT NULL DEFAULT '{}',
    "engagementMetrics" JSONB NOT NULL DEFAULT '{}',
    "successIndicators" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "healthier_sg_contact_integration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointment_contact_integration" (
    "id" TEXT NOT NULL,
    "appointmentId" TEXT UNIQUE NOT NULL,
    "relatedContactIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "contactTriggeredBooking" BOOLEAN NOT NULL DEFAULT false,
    "preAppointmentContact" BOOLEAN NOT NULL DEFAULT true,
    "preContactCompleted" BOOLEAN NOT NULL DEFAULT false,
    "confirmationContact" BOOLEAN NOT NULL DEFAULT true,
    "confirmationSent" BOOLEAN NOT NULL DEFAULT false,
    "followUpContact" BOOLEAN NOT NULL DEFAULT false,
    "followUpCompleted" BOOLEAN NOT NULL DEFAULT false,
    "rescheduleContact" BOOLEAN NOT NULL DEFAULT true,
    "cancellationContact" BOOLEAN NOT NULL DEFAULT true,
    "modificationContact" BOOLEAN NOT NULL DEFAULT true,
    "noShowContact" BOOLEAN NOT NULL DEFAULT false,
    "preOpInstructions" BOOLEAN NOT NULL DEFAULT false,
    "postOpCare" BOOLEAN NOT NULL DEFAULT false,
    "medicationInstructions" BOOLEAN NOT NULL DEFAULT false,
    "resultDiscussion" BOOLEAN NOT NULL DEFAULT false,
    "patientContactPreferences" JSONB NOT NULL DEFAULT '{}',
    "contactSequence" JSONB NOT NULL DEFAULT '[]',
    "contactCompletedSteps" JSONB NOT NULL DEFAULT '[]',
    "clinicContactSystem" BOOLEAN NOT NULL DEFAULT true,
    "doctorContactSystem" BOOLEAN NOT NULL DEFAULT true,
    "patientPortalIntegration" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "appointment_contact_integration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "contact_dashboard_config" (
    "id" TEXT NOT NULL,
    "userId" TEXT UNIQUE NOT NULL,
    "showContactNotifications" BOOLEAN NOT NULL DEFAULT true,
    "showEnquiryUpdates" BOOLEAN NOT NULL DEFAULT true,
    "showAppointmentContacts" BOOLEAN NOT NULL DEFAULT true,
    "showProgramContacts" BOOLEAN NOT NULL DEFAULT false,
    "recentContactsWidget" BOOLEAN NOT NULL DEFAULT true,
    "pendingResponsesWidget" BOOLEAN NOT NULL DEFAULT true,
    "followUpTasksWidget" BOOLEAN NOT NULL DEFAULT true,
    "contactStatsWidget" BOOLEAN NOT NULL DEFAULT false,
    "emailNotifications" BOOLEAN NOT NULL DEFAULT true,
    "smsNotifications" BOOLEAN NOT NULL DEFAULT false,
    "pushNotifications" BOOLEAN NOT NULL DEFAULT true,
    "inAppNotifications" BOOLEAN NOT NULL DEFAULT true,
    "quickContactAccess" BOOLEAN NOT NULL DEFAULT true,
    "contactHistoryAccess" BOOLEAN NOT NULL DEFAULT true,
    "saveContactPreferences" BOOLEAN NOT NULL DEFAULT true,
    "contactAnalyticsAccess" BOOLEAN NOT NULL DEFAULT false,
    "showHealthContacts" BOOLEAN NOT NULL DEFAULT true,
    "showProgramContacts" BOOLEAN NOT NULL DEFAULT false,
    "showAdministrativeContacts" BOOLEAN NOT NULL DEFAULT false,
    "shareContactHistory" BOOLEAN NOT NULL DEFAULT false,
    "allowContactSuggestions" BOOLEAN NOT NULL DEFAULT true,
    "allowContactRecommendations" BOOLEAN NOT NULL DEFAULT false,
    "showClinicContacts" BOOLEAN NOT NULL DEFAULT true,
    "showDoctorContacts" BOOLEAN NOT NULL DEFAULT true,
    "showServiceContacts" BOOLEAN NOT NULL DEFAULT true,
    "showEmergencyContacts" BOOLEAN NOT NULL DEFAULT true,
    "contactListView" BOOLEAN NOT NULL DEFAULT true,
    "contactCardView" BOOLEAN NOT NULL DEFAULT false,
    "contactTimelineView" BOOLEAN NOT NULL DEFAULT false,
    "contactAnalyticsView" BOOLEAN NOT NULL DEFAULT false,
    "enableQuickReply" BOOLEAN NOT NULL DEFAULT true,
    "enableContactEscalation" BOOLEAN NOT NULL DEFAULT false,
    "enableContactMerging" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "contact_dashboard_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "contact_navigation_item" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "activityData" JSONB NOT NULL DEFAULT '{}',
    "priority" "ContactPriority" NOT NULL DEFAULT 'NORMAL',
    "status" "ContactActivityStatus" NOT NULL DEFAULT 'PENDING',
    "integrationData" JSONB NOT NULL DEFAULT '{}',
    "notificationSent" BOOLEAN NOT NULL DEFAULT false,
    "notificationData" JSONB NOT NULL DEFAULT '{}',
    "requiresFollowUp" BOOLEAN NOT NULL DEFAULT false,
    "followUpCompleted" BOOLEAN NOT NULL DEFAULT false,
    "sensitiveData" BOOLEAN NOT NULL DEFAULT false,
    "encrypted" BOOLEAN NOT NULL DEFAULT true,
    "auditTrail" BOOLEAN NOT NULL DEFAULT true,
    "accessLogged" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "contact_navigation_item_pkey" PRIMARY KEY ("id")
);;