-- Migration: healthier_sg_comprehensive_schema
-- Created at: 1762269865

-- CreateEnum
CREATE TYPE "HealthierSGCategory" AS ENUM ('PREVENTIVE_CARE', 'CHRONIC_DISEASE_MANAGEMENT', 'HEALTH_SCREENING', 'LIFESTYLE_INTERVENTION', 'MENTAL_HEALTH', 'MATERNAL_CHILD_HEALTH', 'ELDERLY_CARE', 'REHABILITATION', 'HEALTH_EDUCATION', 'COMMUNITY_HEALTH');

-- CreateEnum
CREATE TYPE "HealthierSGReportingFrequency" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'AS_NEEDED');

-- CreateEnum
CREATE TYPE "HealthierSGEnrollmentMethod" AS ENUM ('ONLINE_SELF_ENROLLMENT', 'CLINIC_ASSISTED', 'REFERRAL', 'GOVERNMENT_INITIATED', 'MOBILE_APP', 'PHONE_CALL', 'WALK_IN', 'HOME_VISIT');

-- CreateEnum
CREATE TYPE "HealthierSGEnrollmentStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'COMPLETED', 'WITHDRAWN', 'EXPIRED', 'PENDING_VERIFICATION', 'REJECTED', 'TRANSFERRED');

-- CreateEnum
CREATE TYPE "HealthierSGEligibilityRuleType" AS ENUM ('AGE_BASED', 'MEDICAL_CONDITION', 'GEOGRAPHIC', 'SOCIOECONOMIC', 'BEHAVIORAL', 'DEMOGRAPHIC', 'LIFESTYLE', 'RISK_ASSESSMENT', 'COMBINATION', 'DYNAMIC');

-- CreateEnum
CREATE TYPE "HealthierSGRecalculationFrequency" AS ENUM ('REAL_TIME', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'EVENT_TRIGGERED');

-- CreateEnum
CREATE TYPE "HealthierSGEvaluationType" AS ENUM ('INITIAL', 'PERIODIC', 'TRIGGERED', 'RE_EVALUATION', 'APPEAL', 'COMPLIANCE', 'QUALITY_ASSURANCE');

-- CreateEnum
CREATE TYPE "HealthierSGEvaluationResult" AS ENUM ('ELIGIBLE', 'NOT_ELIGIBLE', 'CONDITIONAL', 'PENDING_DOCUMENTATION', 'REQUIRES_REVIEW', 'APPEAL_REQUIRED');

-- CreateEnum
CREATE TYPE "HealthierSGBenefitType" AS ENUM ('MONETARY', 'SERVICE_DISCOUNT', 'SUBSIDY', 'REIMBURSEMENT', 'PREVENTIVE_SCREENING', 'HEALTHCARE_SERVICE', 'MEDICATION', 'EQUIPMENT', 'EDUCATION', 'SUPPORT_SERVICE');

-- CreateEnum
CREATE TYPE "HealthierSGBenefitStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'EXPIRED', 'EXHAUSTED', 'PENDING_ACTIVATION', 'UNDER_REVIEW', 'DISPUTED');

-- CreateEnum
CREATE TYPE "HealthierSGBenefitPaymentMechanism" AS ENUM ('DIRECT_PAYMENT', 'REIMBURSEMENT', 'CLAIM_SUBMISSION', 'AUTOMATIC_CREDIT', 'VOUCHER_SYSTEM', 'INSURANCE_CLAIM');

-- CreateEnum
CREATE TYPE "HealthierSGClaimStatus" AS ENUM ('PENDING', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'PAID', 'DISPUTED', 'APPEALED');

-- CreateEnum
CREATE TYPE "HealthierSGClaimSubmissionMethod" AS ENUM ('ONLINE_PORTAL', 'MOBILE_APP', 'EMAIL', 'MAIL', 'IN_PERSON', 'PHONE', 'API_INTEGRATION', 'BATCH_SUBMISSION');

-- CreateEnum
CREATE TYPE "HealthierSGClinicParticipationType" AS ENUM ('FULL_PARTICIPATION', 'SELECTED_SERVICES', 'PILOT_PROGRAM', 'RESEARCH_PARTICIPANT', 'TRAINING_CENTER', 'REFERRAL_PARTNER', 'COLLABORATIVE_CARE');

-- CreateEnum
CREATE TYPE "HealthierSGClinicStatus" AS ENUM ('PENDING', 'APPROVED', 'ACCREDITED', 'SUSPENDED', 'REVOKED', 'EXPIRED', 'UNDER_REVIEW', 'CONDITIONAL_APPROVAL');

-- CreateEnum
CREATE TYPE "HealthierSGClinicAccreditation" AS ENUM ('BASIC', 'STANDARD', 'ADVANCED', 'SPECIALIZED', 'CENTER_OF_EXCELLENCE', 'RESEARCH_CENTER', 'TRAINING_CENTER');

-- CreateEnum
CREATE TYPE "HealthierSGMetricPeriod" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'CAMPAIGN_PERIOD', 'PROGRAM_PHASE');;